name: MLflow CI/CD Retraining Pipeline

on:
    push:
        branches: [ main ]

jobs:
    build-run-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.12"

            - name: Install dependencies
              run: |
                  pip install mlflow==2.19.0 pandas scikit-learn

            - name: Run MLProject
              run: |
                  cd MLProject
                  mlflow run . --env-manager=local

            - name: Upload Artifact to GitHub
              uses: actions/upload-artifact@v4
              with:
                  name: shipping-model
                  path: MLProject/saved_model/

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Bypass Conda TOS
              run: |
                  sed -i 's/- defaults/- conda-forge/g' MLProject/saved_model/conda.yaml

            - name: Build and Push Docker Image
              run: |
                  mlflow models build-docker -m MLProject/saved_model -n ${{ secrets.DOCKERHUB_USERNAME }}/shipping-prediction:latest --env-manager=conda

                  docker push ${{ secrets.DOCKERHUB_USERNAME }}/shipping-prediction:latest
